#!/usr/bin/env zsh

# ==============================================================================
#
#  ___      ___ ________  ________  ________   ________  _____ ______   _______   ________  ___
# |\  \    /  /|\   __  \|\   __  \|\   ___  \|\   ____\|\   _ \  _   \|\  ___ \ |\   __  \|\  \
# \ \  \  /  / | \  \|\  \ \  \|\  \ \  \\ \  \ \  \___|\ \  \\\__\ \  \ \   __/|\ \  \|\  \ \  \
#  \ \  \/  / / \ \   _  _\ \  \\\  \ \  \\ \  \ \  \  __\ \  \\|__| \  \ \  \_|/_\ \   __  \ \  \
#   \ \    / /   \ \  \\  \\ \  \\\  \ \  \\ \  \ \  \|\  \ \  \    \ \  \ \  \_|\ \ \  \ \  \ \  \____
#    \ \__/ /     \ \__\\ _\\ \_______\ \__\\ \__\ \_______\ \__\    \ \__\ \_______\ \__\ \__\ \_______\
#     \|__|/       \|__|\|__|\|_______|\|__| \|__|\|_______|\|__|     \|__|\|_______|\|__|\|__|\|_______|
#
#
# Hello, World! This is the script to execute to setup the system.
#
# The default shell used for running is zsh, since this is what is default on
# and coincidentally what I have been using from the start.
#
# 	./run
#
# ==============================================================================


# ==============================================================================
# Copy all the files in their places
#
dotfiles=(
	.config
	.zshrc
	.p10k.zsh
	.gitconfig
	.gitignore
	.vrongmeal
)
for dotfile in ${dotfiles[*]}
do
	cp -r ${dotfile} ${HOME}
done
#
# ==============================================================================

# ==============================================================================
# Install Homebrew and it's packages
#
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# Install brew packages
brew_installs=(
	neovim
	go
	node
	python3
	wget

	# Ydiff to view diffs side-by-side
	# Even though kitty offers the same in gui, it's not very comfortable to use.
	ydiff
)
for package in ${brew_installs[*]}
do
	brew install ${package}
done

# Brew cask packages
brew_cask_installs=(
	the-unarchiver
	docker
	google-chrome
	kitty
	slowquitapps
)
for package in ${brew_cask_installs[*]}
do
	brew cask install ${package}
done
#
# ==============================================================================

# ==============================================================================
# Setup ZSH
#
# Install Oh My ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

###
source ${HOME}/.zshrc
###

# p10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM}/themes/powerlevel10k
#
# ==============================================================================

# ==============================================================================
# Setup NeoVim
#
# msgpack required by deoplete
pip3 install msgpack

# Vim plug for plugin management
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# [TODO] Install plugins using `:PlugInstall' when running
# Not automating this process since there's a requirement to close vim manually
# when installation of plugins is complete.
#
# ==============================================================================
