font_family SF Mono
font_size 11.5

enabled_layouts splits,stack
map cmd+z goto_layout splits
map cmd+shift+z goto_layout stack
map cmd+shift+d launch --location=hsplit
map cmd+d launch --location=vsplit
map cmd+shift+up move_window up
map cmd+shift+left move_window left
map cmd+shift+right move_window right
map cmd+shift+down move_window down
map cmd+alt+left neighboring_window left
map cmd+alt+right neighboring_window right
map cmd+alt+up neighboring_window up
map cmd+alt+down neighboring_window down

window_border_width 1.0
window_margin_width 0
window_padding_width 5
active_border_color #333333
inactive_border_color #000000
inactive_text_alpha 0.5

tab_bar_edge top
tab_bar_style separator
tab_separator ""
tab_title_template " [ {title} ] "
active_tab_foreground #ffffff
active_tab_background #333333
active_tab_font_style bold
inactive_tab_foreground #cccccc
inactive_tab_background #333333
inactive_tab_font_style normal
tab_bar_background #333333

foreground #ffffff
background #111111
background_opacity 0.9
