# Path to your oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Shell theme
ZSH_THEME="sorin"

# Completion for some-command and some_command is same
HYPHEN_INSENSITIVE="true"

# Prompts for possible auto-correction of commands
ENABLE_CORRECTION="true"

# Display red-dots while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Plugins, git only.
plugins=(git)

# Activate Oh My Zsh
source $ZSH/oh-my-zsh.sh

# SSH key path
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

# -------
# Aliases
# -------

# Use neovim instead of vi(m)
alias vi=nvim
alias vim=nvim

# Use please for sudo (just for fun)
alias please=sudo

# ---

# Locale
export LC_ALL=en_US.UTF-8

# Homebrew
export PATH="/usr/local/sbin:$PATH"

# User bin
export PATH="$PATH:${HOME}/bin"
test -d "${HOME}/bin" || mkdir "${HOME}/bin"

# Golang
export GOPATH="${HOME}/go"
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
test -d "${GOPATH}" || mkdir "${GOPATH}"
test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"

# Ruby
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
