theme = "amberwood_transparent"

[editor]
cursorline = false
shell = ["zsh", "-c"]
line-number = "relative"
color-modes = true
scrolloff = 5
mouse = true
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "all"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = " "

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spacer", "diagnostics", "spinner"]
center = ["file-name"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]

# Make `x` and `X` select the current line (even if it's empty).
#
# These also make the editor go into select mode, which is a little annoying
# but the select mode bindings for `x` and `X` help in extending the selections
# above and below (as expected).
# x = ["goto_line_start", "select_mode", "goto_line_end_newline"]
# X = ["goto_line_start", "select_mode", "goto_line_end_newline"]

x = "extend_line_below"
X = "extend_line_above"

# Whenever going in insert/append mode, remove the selection hints. It's just 
# annoying and never should have been the default.
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]

[keys.select]
";" = ["collapse_selection", "normal_mode"]
"a" = ["collapse_selection", "append_mode"]
"i" = ["collapse_selection", "insert_mode"]

# x and V same as normal mode for select mode.
x = "extend_line_below"
X = "extend_line_above"
V = "extend_to_line_end"

[keys.insert]
"ret" = ["insert_newline", "collapse_selection"]
