theme = "everforest_dark"

[editor]
cursorline = true
shell = ["zsh", "-c"]
line-number = "relative"
color-modes = true
scrolloff = 10
mouse = true
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "all"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = " "

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spacer", "diagnostics", "spinner"]
center = ["file-name"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
# Escape for collapsing selections Enable this if you want to use the same `esc`
# key for everything that ',' and ';' do.
# esc = ["collapse_selection", "keep_primary_selection"]

V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]

# "x" is mapped to the same as below, writing for clearity. Overriding the "X"
# though because it just makes more sense.
x = "extend_line_below"
X = "extend_line_above"

# Whenever going in insert/append mode, remove the selection hints. It's just 
# annoying and never should have been the default.
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]

[keys.select]
";" = ["collapse_selection", "normal_mode"]

# x and V same as normal mode for select mode.
x = "extend_line_below"
X = "extend_line_above"
V = "extend_to_line_end"

[keys.insert]
"ret" = ["insert_newline", "collapse_selection"]
