# Helix language configuration.

[language-server.rust-analyzer]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[[language]]
name = "yaml"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"
